services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql   # данные БД сохраняются между перезапусками
    ports:
      - "3306:3306"

  app:
    build: ./app
    image: node_mysql:v0.1
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: mydb
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"              # UI на localhost:8080
    environment:
      PMA_HOST: db             # имя сервиса MySQL
      PMA_USER: user
      PMA_PASSWORD: userpass
    depends_on:
      - db

volumes:
  db_data:                       # named volume для MySQL
